### ISSUE TITLE
 AssertionError: batch_size cannot be larger than data size

### ISSUE THREAD

**Issue by Jargon4072** [conan7882/VGG-tensorflow#1]
Training network with cifar10 dataset with batch size 128 and testing it using vgg_pretrained.py is giving error:
```
  File "../src/dataflow/base.py", line 83, in next_batch    
    "batch_size cannot be larger than data size"
AssertionError: batch_size cannot be larger than data size"
```
What should be the batch size for training with cifar10 dataset and how to test the trained model with some collected images?

**Comment by pidugusundeep** [comment]
How did you fix this ?? i have the same problem when running `vgg_pretrained.py`
